CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);


CREATE TABLE "Holidays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Holidays" PRIMARY KEY ("Id")
);


CREATE TABLE "LeaveTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text,
    "DefaultAnnualAllowence" integer NOT NULL,
    "MaxCancelableStep" integer,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveTypes" PRIMARY KEY ("Id")
);


CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "TenantId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "TargetUrl" text,
    "IsRead" boolean NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);


CREATE TABLE "TenantLeads" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Message" text,
    "Purpose" integer NOT NULL,
    "RegistrationToken" text NOT NULL,
    "TokenExpiresAt" timestamp with time zone NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TenantLeads" PRIMARY KEY ("Id")
);


CREATE TABLE "Tenants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Domain" text NOT NULL,
    "WeekoffDays" text NOT NULL,
    "DailyInviteLimit" integer NOT NULL,
    "LastQuotaResetDate" timestamp with time zone NOT NULL,
    "RemainingDailyInvites" integer NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Code" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Type" integer NOT NULL,
    "Scope" integer NOT NULL,
    "PermissionsJson" text NOT NULL,
    "DepartmentId" integer,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Roles_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);


CREATE TABLE "LeavePolicies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "Type" integer NOT NULL,
    "ConfigJson" text NOT NULL,
    "LeaveTypeId" integer,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeavePolicies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeavePolicies_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id")
);


CREATE TABLE "WorkflowRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "LeaveTypeId" integer,
    "MinDays" numeric NOT NULL,
    "MaxDays" numeric NOT NULL,
    "CancelLeaveAnyTime" boolean NOT NULL,
    "DisableCancelAfterStep" integer,
    "Priority" integer NOT NULL,
    "Mode" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "ConditionJson" text NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkflowRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkflowRules_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id")
);


CREATE TABLE "BulkUserInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "FileName" text NOT NULL,
    "TotalRows" integer NOT NULL,
    "ProcessedRows" integer NOT NULL,
    "Status" integer NOT NULL,
    "SuccessCount" integer NOT NULL,
    "FailureCount" integer NOT NULL,
    "FilePath" text,
    "ErrorMessage" text,
    "RowResultsJson" text,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BulkUserInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BulkUserInvites_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PolicyScopes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "Name" text NOT NULL,
    "ScopeType" integer NOT NULL,
    "ScopeValue" text NOT NULL,
    "Priority" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "WeekOffPolicyId" integer,
    "UsagePolicyId" integer,
    "BalancePolicyId" integer,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PolicyScopes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PolicyScopes_LeavePolicies_BalancePolicyId" FOREIGN KEY ("BalancePolicyId") REFERENCES "LeavePolicies" ("Id"),
    CONSTRAINT "FK_PolicyScopes_LeavePolicies_UsagePolicyId" FOREIGN KEY ("UsagePolicyId") REFERENCES "LeavePolicies" ("Id"),
    CONSTRAINT "FK_PolicyScopes_LeavePolicies_WeekOffPolicyId" FOREIGN KEY ("WeekOffPolicyId") REFERENCES "LeavePolicies" ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text,
    "Status" integer NOT NULL,
    "Gender" integer NOT NULL,
    "ResetPasswordToken" text,
    "ResetTokenExpiresAt" timestamp with time zone,
    "ManagerId" integer,
    "DepartmentId" integer,
    "RoleId" integer NOT NULL,
    "BulkUserInvitedId" integer,
    "UnresolvedManagerEmail" text,
    "PermissionOverridesJson" text NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_BulkUserInvites_BulkUserInvitedId" FOREIGN KEY ("BulkUserInvitedId") REFERENCES "BulkUserInvites" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "LeaveBalances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "Balance" numeric(18,2) NOT NULL,
    "Year" integer NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveBalances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveBalances_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveBalances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "LeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "Reason" text,
    "RejectionReason" text,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserInvites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "WorkflowSteps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkflowRuleId" integer NOT NULL,
    "Sequence" integer NOT NULL,
    "ApproverType" integer NOT NULL,
    "ApproverValue" text,
    "ApproverId" integer,
    "RoleId" integer,
    "AutoApproveAfterDays" integer NOT NULL,
    "OnTimeout" integer NOT NULL,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkflowSteps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkflowSteps_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id"),
    CONSTRAINT "FK_WorkflowSteps_Users_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WorkflowSteps_WorkflowRules_WorkflowRuleId" FOREIGN KEY ("WorkflowRuleId") REFERENCES "WorkflowRules" ("Id") ON DELETE CASCADE
);


CREATE TABLE "LeaveApprovalSteps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LeaveRequestId" integer NOT NULL,
    "ApproverId" integer,
    "RoleId" integer,
    "Mode" integer NOT NULL,
    "Status" integer NOT NULL,
    "StepOrder" integer NOT NULL,
    "ActionDate" timestamp with time zone,
    "Comments" text,
    "ExternalId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveApprovalSteps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveApprovalSteps_LeaveRequests_LeaveRequestId" FOREIGN KEY ("LeaveRequestId") REFERENCES "LeaveRequests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveApprovalSteps_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id"),
    CONSTRAINT "FK_LeaveApprovalSteps_Users_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES "Users" ("Id")
);


INSERT INTO "Roles" ("Id", "Code", "CreatedAt", "DepartmentId", "Description", "ExternalId", "IsActive", "Name", "PermissionsJson", "Scope", "TenantId", "Type", "UpdatedAt")
VALUES (1, 'SUPER_ADMIN', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'Global system administrator with full access.', '00000000-0000-0000-0000-000000000001', TRUE, 'Super Admin', '[]', 3, NULL, 0, TIMESTAMPTZ '2026-01-01T00:00:00Z');


CREATE INDEX "IX_BulkUserInvites_TenantId" ON "BulkUserInvites" ("TenantId");


CREATE INDEX "IX_LeaveApprovalSteps_ApproverId" ON "LeaveApprovalSteps" ("ApproverId");


CREATE INDEX "IX_LeaveApprovalSteps_LeaveRequestId" ON "LeaveApprovalSteps" ("LeaveRequestId");


CREATE INDEX "IX_LeaveApprovalSteps_RoleId" ON "LeaveApprovalSteps" ("RoleId");


CREATE INDEX "IX_LeaveBalances_LeaveTypeId" ON "LeaveBalances" ("LeaveTypeId");


CREATE INDEX "IX_LeaveBalances_TenantId" ON "LeaveBalances" ("TenantId");


CREATE INDEX "IX_LeaveBalances_UserId" ON "LeaveBalances" ("UserId");


CREATE INDEX "IX_LeavePolicies_LeaveTypeId" ON "LeavePolicies" ("LeaveTypeId");


CREATE INDEX "IX_LeaveRequests_LeaveTypeId" ON "LeaveRequests" ("LeaveTypeId");


CREATE INDEX "IX_LeaveRequests_TenantId" ON "LeaveRequests" ("TenantId");


CREATE INDEX "IX_LeaveRequests_UserId" ON "LeaveRequests" ("UserId");


CREATE INDEX "IX_PolicyScopes_BalancePolicyId" ON "PolicyScopes" ("BalancePolicyId");


CREATE INDEX "IX_PolicyScopes_UsagePolicyId" ON "PolicyScopes" ("UsagePolicyId");


CREATE INDEX "IX_PolicyScopes_WeekOffPolicyId" ON "PolicyScopes" ("WeekOffPolicyId");


CREATE UNIQUE INDEX "IX_Roles_Code" ON "Roles" ("Code");


CREATE INDEX "IX_Roles_DepartmentId" ON "Roles" ("DepartmentId");


CREATE INDEX "IX_Roles_TenantId" ON "Roles" ("TenantId");


CREATE UNIQUE INDEX "IX_TenantLeads_Email" ON "TenantLeads" ("Email");


CREATE UNIQUE INDEX "IX_Tenants_Domain" ON "Tenants" ("Domain");


CREATE INDEX "IX_UserInvites_UserId" ON "UserInvites" ("UserId");


CREATE INDEX "IX_Users_BulkUserInvitedId" ON "Users" ("BulkUserInvitedId");


CREATE INDEX "IX_Users_DepartmentId" ON "Users" ("DepartmentId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX "IX_Users_ManagerId" ON "Users" ("ManagerId");


CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");


CREATE INDEX "IX_Users_TenantId" ON "Users" ("TenantId");


CREATE INDEX "IX_WorkflowRules_LeaveTypeId" ON "WorkflowRules" ("LeaveTypeId");


CREATE INDEX "IX_WorkflowSteps_ApproverId" ON "WorkflowSteps" ("ApproverId");


CREATE INDEX "IX_WorkflowSteps_RoleId" ON "WorkflowSteps" ("RoleId");


CREATE INDEX "IX_WorkflowSteps_WorkflowRuleId" ON "WorkflowSteps" ("WorkflowRuleId");


SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);


